# Generated by Django 5.1.2 on 2024-10-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=25)),
                ('duracion', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
            ],
        ),
    ]
