# Generated by Django 5.1.2 on 2024-10-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vestido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=25)),
                ('escote', models.CharField(max_length=20)),
                ('mangas', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='viajes',
        ),
    ]
